name: "GitHub Action to unlock git-crypt secrets"
description: "Unlock git-crypt files with a simple alpine based Docker image"
author: "Arnaud Rinquin & Diego García"
branding:
  icon: "unlock"
  color: "green"
runs:
  using: "docker"
  image: "Dockerfile"
